### ISSUE TITLE
插件破坏了分享歌曲到新浪微博的内容和链接

### ISSUE THREAD

**Issue by piglei** [piglei/fmx163#9]

**Comment by Ra1nWarden** [comment]
这个研究了好久，[这里](http://s.doubanio.com/f/fm/891ebd001d38ea3d5af132dfe8dde84c139cc400/js/fm/fm_share.js)有个拿歌曲信息的js，好像是`window.FM`是`null`，找了半天也没发现哪里define的这个variable。求指导方向……

**Comment by piglei** [comment]
我早上花了点时间看了一下找到bug了，已修复，是我patch douban的一个方法不当造成的：
https://github.com/piglei/fmx163/commit/9266b14d0cd3b22321b7afed0494f138cfabc6e8#diff-150ad6f1771077847811ece50090bf52L44

谢谢你的关注，将发布新版。
